=== hongbinbao/igastc-pyrunner-release/stability.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.intel.com"
xmlns="http://www.intel.com"
elementFormDefault="qualified">
<xs:element name="test_plan">
	<xs:complexType>
	    <xs:sequence>
  	        <xs:element name="component" maxOccurs="unbounded">
  	        	<xs:complexType>
  	        		<xs:sequence>
  	        		    <xs:element name="testcase" maxOccurs="unbounded">
  	        			    <xs:complexType>
  	                      <xs:attribute name="test_script_entry" type="xs:string" use="required"/>
  	                      <xs:attribute name="purpose" type="xs:string" use="required"/>
  	                      <xs:attribute name="loop" type="xs:positiveInteger" use="required"/>
                          <xs:attribute name="timeout" type="xs:positiveInteger" use="required"/>
  	        			    </xs:complexType>
  	        		    </xs:element>
  	        	  </xs:sequence>
  	  	        <xs:attribute name="name" type="xs:string" use="required"/>
  	        	</xs:complexType>
  	        </xs:element>
  	    </xs:sequence>
  	</xs:complexType>
</xs:element>

</xs:schema>

=== hongbinbao/igastc-pyrunner-release/original_plan.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_plan xmlns="http://www.intel.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.intel.com stability.xsd">
  <suite name="test-suite">
   <component name="telephony">
     <testcase test_script_entry="ChkPhone_Launch.sh" purpose="Check phone launch" loop="2" execution_type="auto" timeout="120"/>
     <testcase test_script_entry="ChkSettings_Launch.sh" purpose="Check setting launch" loop="2" execution_type="auto" timeout="120"/>
   </component>
   <component name="PIM">
     <testcase test_script_entry="ChkClock_Launch.sh" purpose="Check alarmCLock launch" loop="3" execution_type="auto" timeout="90"/>
   </component>
   <component name="browser">
     <testcase test_script_entry="ChkBrowser_Launch.sh" purpose="Check browser launch" loop="2" execution_type="auto" timeout="120"/>
     <testcase test_script_entry="ChkBrowserSettings_Launch.sh" purpose="Check browser setting launch" execution_type="auto" loop="2" timeout="120"/>
   </component>
   <component name="Sync">
     <testcase test_script_entry="ChkCalendar_Launch.sh" purpose="Check calendar launch" loop="3" execution_type="auto" timeout="90"/>
   </component>
 </suite>
</test_plan>
